In [3]:
import numpy as np
import pandas as pd

Considere os arrays numpy X, y abaixo:

In [4]:
from sklearn.datasets import load_iris

X = load_iris().data
y = load_iris().target

In [5]:
X[:10]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1]])

In [6]:
y[:10]

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

Concatenando os arrays numpy

In [7]:
arr_c_ = np.c_[X,y]
print(arr_c_)
print(arr_c_.shape)

[[5.1 3.5 1.4 0.2 0. ]
 [4.9 3.  1.4 0.2 0. ]
 [4.7 3.2 1.3 0.2 0. ]
 [4.6 3.1 1.5 0.2 0. ]
 [5.  3.6 1.4 0.2 0. ]
 [5.4 3.9 1.7 0.4 0. ]
 [4.6 3.4 1.4 0.3 0. ]
 [5.  3.4 1.5 0.2 0. ]
 [4.4 2.9 1.4 0.2 0. ]
 [4.9 3.1 1.5 0.1 0. ]
 [5.4 3.7 1.5 0.2 0. ]
 [4.8 3.4 1.6 0.2 0. ]
 [4.8 3.  1.4 0.1 0. ]
 [4.3 3.  1.1 0.1 0. ]
 [5.8 4.  1.2 0.2 0. ]
 [5.7 4.4 1.5 0.4 0. ]
 [5.4 3.9 1.3 0.4 0. ]
 [5.1 3.5 1.4 0.3 0. ]
 [5.7 3.8 1.7 0.3 0. ]
 [5.1 3.8 1.5 0.3 0. ]
 [5.4 3.4 1.7 0.2 0. ]
 [5.1 3.7 1.5 0.4 0. ]
 [4.6 3.6 1.  0.2 0. ]
 [5.1 3.3 1.7 0.5 0. ]
 [4.8 3.4 1.9 0.2 0. ]
 [5.  3.  1.6 0.2 0. ]
 [5.  3.4 1.6 0.4 0. ]
 [5.2 3.5 1.5 0.2 0. ]
 [5.2 3.4 1.4 0.2 0. ]
 [4.7 3.2 1.6 0.2 0. ]
 [4.8 3.1 1.6 0.2 0. ]
 [5.4 3.4 1.5 0.4 0. ]
 [5.2 4.1 1.5 0.1 0. ]
 [5.5 4.2 1.4 0.2 0. ]
 [4.9 3.1 1.5 0.2 0. ]
 [5.  3.2 1.2 0.2 0. ]
 [5.5 3.5 1.3 0.2 0. ]
 [4.9 3.6 1.4 0.1 0. ]
 [4.4 3.  1.3 0.2 0. ]
 [5.1 3.4 1.5 0.2 0. ]
 [5.  3.5 1.3 0.3 0. ]
 [4.5 2.3 1.3 0.3 0. ]
 [4.4 3.2 1.3 0.2 0. ]
 [5.  3.5 1

Transformando o array final em dataframe

In [8]:
df = pd.DataFrame(data=arr_c_)
print(df)

       0    1    2    3    4
0    5.1  3.5  1.4  0.2  0.0
1    4.9  3.0  1.4  0.2  0.0
2    4.7  3.2  1.3  0.2  0.0
3    4.6  3.1  1.5  0.2  0.0
4    5.0  3.6  1.4  0.2  0.0
..   ...  ...  ...  ...  ...
145  6.7  3.0  5.2  2.3  2.0
146  6.3  2.5  5.0  1.9  2.0
147  6.5  3.0  5.2  2.0  2.0
148  6.2  3.4  5.4  2.3  2.0
149  5.9  3.0  5.1  1.8  2.0

[150 rows x 5 columns]


Alterando nome das colunas para 'X1', 'X2', 'X3', 'X4', 'target'

In [9]:
df.set_axis(['X1','X2','X3','X4','target'], axis=1, inplace=True)
df

X1   X2   X3   X4  target
0    5.1  3.5  1.4  0.2     0.0
1    4.9  3.0  1.4  0.2     0.0
2    4.7  3.2  1.3  0.2     0.0
3    4.6  3.1  1.5  0.2     0.0
4    5.0  3.6  1.4  0.2     0.0
..   ...  ...  ...  ...     ...
145  6.7  3.0  5.2  2.3     2.0
146  6.3  2.5  5.0  1.9     2.0
147  6.5  3.0  5.2  2.0     2.0
148  6.2  3.4  5.4  2.3     2.0
149  5.9  3.0  5.1  1.8     2.0

[150 rows x 5 columns]

__Exercício 2:__ Usando o df criado no exercício 1, calcule qual a média da variável 'X2', para cada valor de target. Dica: Use a função groupby no dataframe df para resolver.

In [10]:
media = df.groupby(['X2', 'target'])['X2'].mean()
print(media)

X2   target
2.0  1.0       2.0
2.2  1.0       2.2
     2.0       2.2
2.3  0.0       2.3
     1.0       2.3
2.4  1.0       2.4
2.5  1.0       2.5
     2.0       2.5
2.6  1.0       2.6
     2.0       2.6
2.7  1.0       2.7
     2.0       2.7
2.8  1.0       2.8
     2.0       2.8
2.9  0.0       2.9
     1.0       2.9
     2.0       2.9
3.0  0.0       3.0
     1.0       3.0
     2.0       3.0
3.1  0.0       3.1
     1.0       3.1
     2.0       3.1
3.2  0.0       3.2
     1.0       3.2
     2.0       3.2
3.3  0.0       3.3
     1.0       3.3
     2.0       3.3
3.4  0.0       3.4
     1.0       3.4
     2.0       3.4
3.5  0.0       3.5
3.6  0.0       3.6
     2.0       3.6
3.7  0.0       3.7
3.8  0.0       3.8
     2.0       3.8
3.9  0.0       3.9
4.0  0.0       4.0
4.1  0.0       4.1
4.2  0.0       4.2
4.4  0.0       4.4
Name: X2, dtype: float64


__Exercício 4:__ 


4.1: Filtre o dataframe df onde X1 é maior do que 6 __ou__ target é diferente de 2 e chame-o de df1. Dica: usar os filtros e os operadores vistos em aula;

4.2: Filtre os primeiros 15 índices do dataframe df e chame-o de df2;

4.3: Transformando os dataframes df1 e df2 para arrays. Multiplique df1 pelo transposto de df2 (use a função que calcula transposta de matriz) e printe o resultado final. Lembre-se de dropar a coluna target_2 de cada um dos dataframes antes de fazer a mutliplicação.

> 4.1.   Filtre o dataframe df onde X1 é maior do que 6 **ou** target é diferente de 2 e chame-o de df1








In [11]:
df1 = df[(df.X1>6) & (df.target!=2)]



> 4.2: Filtre os primeiros 15 índices do dataframe df e chame-o de df2


In [12]:
df[:15]

X1   X2   X3   X4  target
0   5.1  3.5  1.4  0.2     0.0
1   4.9  3.0  1.4  0.2     0.0
2   4.7  3.2  1.3  0.2     0.0
3   4.6  3.1  1.5  0.2     0.0
4   5.0  3.6  1.4  0.2     0.0
5   5.4  3.9  1.7  0.4     0.0
6   4.6  3.4  1.4  0.3     0.0
7   5.0  3.4  1.5  0.2     0.0
8   4.4  2.9  1.4  0.2     0.0
9   4.9  3.1  1.5  0.1     0.0
10  5.4  3.7  1.5  0.2     0.0
11  4.8  3.4  1.6  0.2     0.0
12  4.8  3.0  1.4  0.1     0.0
13  4.3  3.0  1.1  0.1     0.0
14  5.8  4.0  1.2  0.2     0.0

In [14]:
df2 = df[:15]



> 4.3: Transformando os dataframes df1 e df2 para arrays. Multiplique df1 pelo transposto de df2 (use a função que calcula transposta de matriz) e printe o resultado final. Lembre-se de dropar a coluna target_2 de cada um dos dataframes antes de fazer a mutliplicação.





> dropar a coluna target_2 de cada um dos dataframes antes de fazer a mutliplicação






In [13]:
df1 = df1.drop(["target"], axis=1)
df1.head()

X1   X2   X3   X4
50  7.0  3.2  4.7  1.4
51  6.4  3.2  4.5  1.5
52  6.9  3.1  4.9  1.5
54  6.5  2.8  4.6  1.5
56  6.3  3.3  4.7  1.6

In [15]:
df2 = df2.drop(["target"], axis=1)
df2.head()

X1   X2   X3   X4
0  5.1  3.5  1.4  0.2
1  4.9  3.0  1.4  0.2
2  4.7  3.2  1.3  0.2
3  4.6  3.1  1.5  0.2
4  5.0  3.6  1.4  0.2



> Transformando os dataframes df1 e df2 para arrays



In [16]:
arr_1 = df1.values
arr_2 = df2.values



> Multiplique df1 pelo transposto de df2 (use a função que calcula transposta de matriz) e printe o resultado final



In [17]:
arr_2_trans = arr_2.T
print(arr_2_trans)

[[5.1 4.9 4.7 4.6 5.  5.4 4.6 5.  4.4 4.9 5.4 4.8 4.8 4.3 5.8]
 [3.5 3.  3.2 3.1 3.6 3.9 3.4 3.4 2.9 3.1 3.7 3.4 3.  3.  4. ]
 [1.4 1.4 1.3 1.5 1.4 1.7 1.4 1.5 1.4 1.5 1.5 1.6 1.4 1.1 1.2]
 [0.2 0.2 0.2 0.2 0.2 0.4 0.3 0.2 0.2 0.1 0.2 0.2 0.1 0.1 0.2]]


In [18]:
print(np.dot(arr_1,arr_2_trans))

[[53.76 50.76 49.53 49.45 53.38 58.83 50.08 53.21 46.94 51.41 56.97 52.28
  49.92 45.01 59.32]
 [50.44 47.56 46.47 46.41 50.12 55.29 47.07 49.93 44.04 48.18 53.45 49.1
  46.77 42.22 55.62]
 [53.2  50.27 49.02 49.   52.82 58.28 49.59 52.69 46.51 50.92 56.38 51.8
  49.43 44.51 58.6 ]
 [49.69 46.99 45.79 45.78 49.32 54.44 46.31 49.22 43.46 47.58 52.66 48.38
  46.19 41.56 54.72]
 [50.58 47.67 46.6  46.58 50.28 55.52 47.26 50.09 44.19 48.31 53.6  49.3
  46.88 42.32 55.7 ]
 [50.51 47.74 46.54 46.51 50.14 55.29 47.05 50.02 44.15 48.36 53.53 49.16
  46.95 42.27 55.66]
 [48.12 45.45 44.34 44.38 47.8  52.8  44.92 47.69 42.11 46.07 51.   46.94
  44.7  40.24 52.9 ]
 [51.46 48.57 47.41 47.31 51.1  56.31 47.94 50.92 44.91 49.18 54.53 50.02
  47.76 43.09 56.82]
 [45.92 43.58 42.33 42.39 45.52 50.31 42.75 45.53 40.26 44.1  48.67 44.74
  42.81 38.36 50.46]
 [46.77 44.15 43.09 43.   46.44 51.18 43.57 46.28 40.82 44.7  49.56 45.46
  43.41 39.16 51.64]
 [48.04 45.53 44.28 44.38 47.66 52.7  44.79 47.65 42.

__Exercício 3:__ Construa um dicionário mapeando os valores:
        
        0 - 'A'
        
        1 - 'B'
        
        2 - 'C'
        
Usando a função map, crie uma coluna nova no dataframe df chamada 'target_2' com o mapeamento feito. Dica: Use a função map como visto em aula.



> Criando a biblioteca de referência para a função map()



In [19]:
target_2 = {0:"A", 1:"B", 2:"C"}
print(target_2)

{0: 'A', 1: 'B', 2: 'C'}




> Criando a nova coluna "target_2" com os valores do mapeamento no dataframe



In [20]:
target_2 = {0:"A", 1:"B", 2:"C"}
df["target_2"] = df["target"].map(target_2)
print(df)


      X1   X2   X3   X4  target target_2
0    5.1  3.5  1.4  0.2     0.0        A
1    4.9  3.0  1.4  0.2     0.0        A
2    4.7  3.2  1.3  0.2     0.0        A
3    4.6  3.1  1.5  0.2     0.0        A
4    5.0  3.6  1.4  0.2     0.0        A
..   ...  ...  ...  ...     ...      ...
145  6.7  3.0  5.2  2.3     2.0        C
146  6.3  2.5  5.0  1.9     2.0        C
147  6.5  3.0  5.2  2.0     2.0        C
148  6.2  3.4  5.4  2.3     2.0        C
149  5.9  3.0  5.1  1.8     2.0        C

[150 rows x 6 columns]


__Exercício 5:__ 
    
5.1: Crie uma função que receba um  número inteiro positivo N e retorne um array 0, 1, ..., N. Dica: Use as funções que vimos para criação de arrays;
    
5.2: Crie uma função que receba um array [0,1, .., N] e retorne o mesmo array, só que com os números em posições aleatórias. Dica: use a função que vimos em aula que faz escolhas aleatórias SEM reposição;

5.3: Crie uma função que receba um número inteiro positivo N. Essa função deve retornar um array de tamanho N, cujos valores são números inteiros entre 0 e N-1 e pode haver repetição desses números.



> 5.1: Crie uma função que receba um número inteiro positivo N e retorne um array 0, 1, ..., N. Dica: Use as funções que vimos para criação de arrays



In [21]:
def criar_array(N):
  array = np.arange(0,N)
  return array

In [22]:
criar_array(100)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])



> 5.2: Crie uma função que receba um array [0,1, .., N] e retorne o mesmo array, só que com os números em posições aleatórias. Dica: use a função que vimos em aula que faz escolhas aleatórias SEM reposição




In [23]:
def criar_array_aleatorio(array):
  np.random.shuffle(array)
  return array

In [24]:
criar_array_aleatorio([10,5,3,12])

[12, 3, 5, 10]



> 5.3: Crie uma função que receba um número inteiro positivo N. Essa função deve retornar um array de tamanho N, cujos valores são números inteiros entre 0 e N-1 e pode haver repetição desses números



In [25]:
def criar_array2(N):
  array = np.arange(0,N-1)
  repeat = True
  return array

In [26]:
criar_array2(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

__Exercício 6:__ Construa uma função divide_dados:
        
        - recebe um array X de dimensões quaisquer (n,k) e um parâmetro p entre 0 e 1.
        - divide o array X em duas partes disjuntas de forma aleatória. Ou seja, crie dois novos arrays, X1 e X2,
        onde a dimensão de linhas de X1 somada com a dimensão de linhas de X2 deve ser igual a dimensão de linhas de X.
        - interpretando p como percentual, o tamanho de X1 deve ser p*100% do número de linhas de X; enquanto X2 deve ser o resto.
        - retorne esses dois arrays.
        
       

In [27]:
def divide_dados(array,p):
  tamanho = int(p*len(array))
  x1 = array[:tamanho]
  x2 = array[tamanho:]
  return x1, x2


In [28]:
divide_dados([6, 2, 1, 8, 0, 3, 9, 5, 4, 7], 0.8)

([6, 2, 1, 8, 0, 3, 9, 5], [4, 7])