# Exercícios:

<br>

1 - Importe o arquivo "dataframe_exercicio_modulo_7.csv" em um dataframe - df - do Pandas.

<br>

2 - Quais as dimensões do dataframe?

<br>

3 - Qual o tipo das variáveis?

<br>

4 - Existem variáveis faltantes no dataset? Quais?

<br>


5 - Exiba todas as categorias das variáveis 'estado_civil', 'cor' e 'sexo'. Você consegue detectar algum problema?

<br>

6 - Faça um tratamento nas variáveis faltantes.

<br>

7 - Aplique uma transformação "MinMax" na variável  'tempo_educacao'e uma transformação "StandardScaler" na variável 'horas_por_semana'.

<br>

8 - Aplique ohe-hot-encoding nas variáveis 'estado_civil', 'cor' e 'sexo'.

<br>

9 - Detecte e elimine os outliers da variável 'idade'.

<br>


10 - Escreva uma função que receba o dataframe em sua forma original e retorne o dataframe modificado, após todas as transformações dos itens acima.

**1 - Importe o arquivo "dataframe_exercicio_modulo_7.csv" em um dataframe - df - do Pandas**

In [112]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [113]:
from google.colab import files
uploaded = files.upload()

Saving dataframe_exercicio_modulo_7.csv to dataframe_exercicio_modulo_7 (3).csv


In [114]:
import io
df = pd.read_csv(io.BytesIO(uploaded['dataframe_exercicio_modulo_7.csv']))
df.head()

idade  tempo_educacao        estado_civil    cor    sexo  horas_por_semana  \
0   39.0              13       Never-married  White    Male                40   
1   50.0              13  Married-civ-spouse  White    Male                13   
2   38.0               9            Divorced  White    Male                40   
3   53.0               7  Married-civ-spouse  Black    Male                40   
4   37.0              14  Married-civ-spouse  White  Female                40   

  salario_anual  nome  dívida  
0         <=50K   NaN     NaN  
1         <=50K   NaN     NaN  
2         <=50K   NaN     NaN  
3         <=50K   NaN     NaN  
4         <=50K   NaN     NaN

In [115]:
print(df)

       idade  tempo_educacao        estado_civil    cor    sexo  \
0       39.0              13       Never-married  White    Male   
1       50.0              13  Married-civ-spouse  White    Male   
2       38.0               9            Divorced  White    Male   
3       53.0               7  Married-civ-spouse  Black    Male   
4       37.0              14  Married-civ-spouse  White  Female   
...      ...             ...                 ...    ...     ...   
29165   27.0              12  Married-civ-spouse  White  Female   
29166   40.0               9  Married-civ-spouse  White    Male   
29167   58.0               9             Widowed  White  Female   
29168   22.0               9       Never-married  White    Male   
29169   52.0               9  Married-civ-spouse  White  Female   

       horas_por_semana salario_anual  nome  dívida  
0                    40         <=50K   NaN     NaN  
1                    13         <=50K   NaN     NaN  
2                    40         <

**2 - Quais as dimensões do dataframe?**

In [116]:
df.describe()

idade  tempo_educacao  horas_por_semana  nome  dívida
count  29071.000000    29170.000000      29170.000000   0.0     0.0
mean      38.654088       10.169455         40.447755   NaN     NaN
std       13.720345        2.394966         12.417203   NaN     NaN
min       17.000000        1.000000          1.000000   NaN     NaN
25%       28.000000        9.000000         40.000000   NaN     NaN
50%       37.000000       10.000000         40.000000   NaN     NaN
75%       48.000000       12.000000         45.000000   NaN     NaN
max       90.000000       16.000000         99.000000   NaN     NaN

In [117]:
print(df.shape)

(29170, 9)


29170 - linhas
e
9 colunas

**3 - Qual o tipo das variáveis?**

In [118]:
print(df.columns)

Index(['idade', 'tempo_educacao', 'estado_civil', 'cor', 'sexo',
       'horas_por_semana', 'salario_anual', 'nome', 'dívida'],
      dtype='object')


Variáveis númericas: Idade, Tempo de Educação, Horas por Semana, Salário Anual e Dívida. 

Variáveis categóricas: Estado Civil, Cor, Sexo e Nome.

**4 - Existem variáveis faltantes no dataset? Quais?**

In [119]:
df.isnull().sum()

idade                  99
tempo_educacao          0
estado_civil            0
cor                     0
sexo                    0
horas_por_semana        0
salario_anual           0
nome                29170
dívida              29170
dtype: int64

In [120]:
df.count()

idade               29071
tempo_educacao      29170
estado_civil        29170
cor                 29170
sexo                29170
horas_por_semana    29170
salario_anual       29170
nome                    0
dívida                  0
dtype: int64

Faltam os dados das variáveis 'Idade', 'Nome' e 'Dívida'.

**5 - Exiba todas as categorias das variáveis 'estado_civil', 'cor' e 'sexo'. Você consegue detectar algum problema?**

In [121]:
(df.estado_civil).unique()

array(['Never-married', 'Married-civ-spouse', 'Divorced', 'Separated',
       'Married-AF-spouse', 'Widowed', 'Married-spouse-absent'],
      dtype=object)

In [122]:
(df.cor).unique()

array(['White', 'Black', 'Other', 'Asian-Pac-Islander',
       'Amer-Indian-Eskimo'], dtype=object)

In [123]:
(df.sexo).unique()

array(['Male', 'Female', '?'], dtype=object)

**6 - Faça um tratamento nas variáveis faltantes.**

variáveis faltantes: Idade, Nome e Dívida



> Tratando os dados faltantes na variável 'Idade' a partir do uso da média





In [124]:
media_idade = df.idade.mean()
media_idade

38.654088266657496

In [125]:
df.idade.loc[np.isnan(df.idade)]

116     NaN
523     NaN
733     NaN
771     NaN
985     NaN
         ..
27743   NaN
27778   NaN
27878   NaN
27883   NaN
28326   NaN
Name: idade, Length: 99, dtype: float64

In [126]:
df.idade.fillna(media_idade)

0        39.0
1        50.0
2        38.0
3        53.0
4        37.0
         ... 
29165    27.0
29166    40.0
29167    58.0
29168    22.0
29169    52.0
Name: idade, Length: 29170, dtype: float64

In [132]:
df.idade.fillna(-1)

0        39.0
1        50.0
2        38.0
3        53.0
4        37.0
         ... 
29165    27.0
29166    40.0
29167    58.0
29168    22.0
29169    52.0
Name: idade, Length: 29170, dtype: float64

In [128]:
df_limpo = df

In [134]:
df_limpo.idade = df_limpo.idade.fillna(media_idade)

In [135]:
df_limpo

idade  tempo_educacao        estado_civil    cor    sexo  \
0       39.0              13       Never-married  White    Male   
1       50.0              13  Married-civ-spouse  White    Male   
2       38.0               9            Divorced  White    Male   
3       53.0               7  Married-civ-spouse  Black    Male   
4       37.0              14  Married-civ-spouse  White  Female   
...      ...             ...                 ...    ...     ...   
29165   27.0              12  Married-civ-spouse  White  Female   
29166   40.0               9  Married-civ-spouse  White    Male   
29167   58.0               9             Widowed  White  Female   
29168   22.0               9       Never-married  White    Male   
29169   52.0               9  Married-civ-spouse  White  Female   

       horas_por_semana salario_anual  nome  dívida  
0                    40         <=50K   NaN     NaN  
1                    13         <=50K   NaN     NaN  
2                    40         <=50K   NaN     NaN  
3                    40         <=50K   NaN     NaN  
4                    40         <=50K   NaN     NaN  
...                 ...           ...   ...     ...  
29165                38         <=50K   NaN     NaN  
29166                40          >50K   NaN     NaN  
29167                40         <=50K   NaN     NaN  
29168                20         <=50K   NaN     NaN  
29169                40          >50K   NaN     NaN  

[29170 rows x 9 columns]



> Tratando a variável 'Nome'



In [142]:
df.nome.loc[np.isnan(df.nome)] #localizando as linhas que possuem valores faltantes

0       NaN
1       NaN
2       NaN
3       NaN
4       NaN
         ..
29165   NaN
29166   NaN
29167   NaN
29168   NaN
29169   NaN
Name: nome, Length: 29170, dtype: float64

In [141]:
#preenchendo esses valores com um nome padrão
df.nome.fillna('João')

0        João
1        João
2        João
3        João
4        João
         ... 
29165    João
29166    João
29167    João
29168    João
29169    João
Name: nome, Length: 29170, dtype: object

In [138]:
df.nome.fillna(-1)

0       -1.0
1       -1.0
2       -1.0
3       -1.0
4       -1.0
        ... 
29165   -1.0
29166   -1.0
29167   -1.0
29168   -1.0
29169   -1.0
Name: nome, Length: 29170, dtype: float64



> Tratando a variável 'Dívida' preenchendo os valores faltantes com '-1' porque não há valor algum na coluna para cálculo de média



In [143]:
df.dívida.fillna(-1)

0       -1.0
1       -1.0
2       -1.0
3       -1.0
4       -1.0
        ... 
29165   -1.0
29166   -1.0
29167   -1.0
29168   -1.0
29169   -1.0
Name: dívida, Length: 29170, dtype: float64

**7 - Aplique uma transformação "MinMax" na variável  'tempo_educacao' e uma transformação "StandardScaler" na variável 'horas_por_semana'.**



> Transformação "MinMax" na variável  'tempo_educacao'


In [144]:
from sklearn.preprocessing import MinMaxScaler, StandardScaler

In [145]:
mm_scaler = MinMaxScaler()
ss_scaler = StandardScaler()

In [146]:
X = df.tempo_educacao.values.reshape(-1,1)
X

array([[13],
       [13],
       [ 9],
       ...,
       [ 9],
       [ 9],
       [ 9]])

In [147]:
mm_scaler.fit(X)

MinMaxScaler()

In [148]:
mm_scaler.transform(X)

array([[0.8       ],
       [0.8       ],
       [0.53333333],
       ...,
       [0.53333333],
       [0.53333333],
       [0.53333333]])



> transformação "StandardScaler" na variável 'horas_por_semana'



In [149]:
X2 = df.horas_por_semana.values.reshape(-1,1)
X2

array([[40],
       [13],
       [40],
       ...,
       [40],
       [20],
       [40]])

In [150]:
ss_scaler.fit(X2)

StandardScaler()

In [151]:
ss_scaler.transform(X2)

array([[-0.03605983],
       [-2.21049975],
       [-0.03605983],
       ...,
       [-0.03605983],
       [-1.64675606],
       [-0.03605983]])

**8 - Aplique ohe-hot-encoding nas variáveis 'estado_civil', 'cor' e 'sexo'.**



> Variável 'estado_civil'



In [152]:
from sklearn.preprocessing import OneHotEncoder
ohe = OneHotEncoder()

In [153]:
variavel_ohe = df.estado_civil.values.reshape(-1,1)

ohe.fit(variavel_ohe)

OneHotEncoder()

In [154]:
ohe.transform(variavel_ohe)

<29170x7 sparse matrix of type '<class 'numpy.float64'>'
	with 29170 stored elements in Compressed Sparse Row format>

In [155]:
ohe.transform(variavel_ohe).toarray()

array([[0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 1.],
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.]])

In [156]:
ohe.categories_

[array(['Divorced', 'Married-AF-spouse', 'Married-civ-spouse',
        'Married-spouse-absent', 'Never-married', 'Separated', 'Widowed'],
       dtype=object)]

In [157]:
dataframe_OHE = pd.DataFrame(ohe.transform(variavel_ohe).toarray(), 
                             columns = ohe.categories_[0].tolist())
dataframe_OHE

Divorced  Married-AF-spouse  Married-civ-spouse  Married-spouse-absent  \
0           0.0                0.0                 0.0                    0.0   
1           0.0                0.0                 1.0                    0.0   
2           1.0                0.0                 0.0                    0.0   
3           0.0                0.0                 1.0                    0.0   
4           0.0                0.0                 1.0                    0.0   
...         ...                ...                 ...                    ...   
29165       0.0                0.0                 1.0                    0.0   
29166       0.0                0.0                 1.0                    0.0   
29167       0.0                0.0                 0.0                    0.0   
29168       0.0                0.0                 0.0                    0.0   
29169       0.0                0.0                 1.0                    0.0   

       Never-married  Separated  Widowed  
0                1.0        0.0      0.0  
1                0.0        0.0      0.0  
2                0.0        0.0      0.0  
3                0.0        0.0      0.0  
4                0.0        0.0      0.0  
...              ...        ...      ...  
29165            0.0        0.0      0.0  
29166            0.0        0.0      0.0  
29167            0.0        0.0      1.0  
29168            1.0        0.0      0.0  
29169            0.0        0.0      0.0  

[29170 rows x 7 columns]



> Variável 'cor'



In [158]:
variavel_ohe = df.cor.values.reshape(-1,1)
ohe.fit(variavel_ohe)
ohe.transform(variavel_ohe)
ohe.transform(variavel_ohe).toarray()


array([[0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 1.],
       ...,
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 1.]])

In [159]:
ohe.categories_

[array(['Amer-Indian-Eskimo', 'Asian-Pac-Islander', 'Black', 'Other',
        'White'], dtype=object)]

In [160]:
dataframe_OHE = pd.DataFrame(ohe.transform(variavel_ohe).toarray(), 
                             columns = ohe.categories_[0].tolist())
dataframe_OHE

Amer-Indian-Eskimo  Asian-Pac-Islander  Black  Other  White
0                     0.0                 0.0    0.0    0.0    1.0
1                     0.0                 0.0    0.0    0.0    1.0
2                     0.0                 0.0    0.0    0.0    1.0
3                     0.0                 0.0    1.0    0.0    0.0
4                     0.0                 0.0    0.0    0.0    1.0
...                   ...                 ...    ...    ...    ...
29165                 0.0                 0.0    0.0    0.0    1.0
29166                 0.0                 0.0    0.0    0.0    1.0
29167                 0.0                 0.0    0.0    0.0    1.0
29168                 0.0                 0.0    0.0    0.0    1.0
29169                 0.0                 0.0    0.0    0.0    1.0

[29170 rows x 5 columns]

Variável 'sexo'

In [161]:
variavel_ohe = df.sexo.values.reshape(-1,1)
ohe.fit(variavel_ohe)
ohe.transform(variavel_ohe)
ohe.transform(variavel_ohe).toarray()

array([[0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       ...,
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.]])

In [162]:
ohe.categories_

[array(['?', 'Female', 'Male'], dtype=object)]

In [163]:
dataframe_OHE = pd.DataFrame(ohe.transform(variavel_ohe).toarray(), 
                             columns = ohe.categories_[0].tolist())
dataframe_OHE

?  Female  Male
0      0.0     0.0   1.0
1      0.0     0.0   1.0
2      0.0     0.0   1.0
3      0.0     0.0   1.0
4      0.0     1.0   0.0
...    ...     ...   ...
29165  0.0     1.0   0.0
29166  0.0     0.0   1.0
29167  0.0     1.0   0.0
29168  0.0     0.0   1.0
29169  0.0     1.0   0.0

[29170 rows x 3 columns]

**9 - Detecte e elimine os outliers da variável 'idade'.**

In [164]:
iqr = np.percentile(df_limpo.idade, 75) - np.percentile(df_limpo.idade, 25)
iqr

20.0

In [165]:
limite_inf = np.maximum(np.percentile(df_limpo.idade, 25) - 1.5 * iqr, np.min(df_limpo.idade))
limite_inf

17.0

In [166]:
limite_sup = np.minimum(np.percentile(df_limpo.idade, 75) + 1.5 * iqr, np.max(df_limpo.idade))
limite_sup

78.0

In [167]:
def detecta_outlier(x, limite = 1.5):
    iqr = np.percentile(x, 75) - np.percentile(x, 25)
    limite_inf = np.maximum(np.percentile(x, 25) - limite * iqr, np.min(x))
    limite_sup = np.minimum(np.percentile(x, 75) + limite * iqr, np.max(x))
    return np.where((x < limite_inf) | (x > limite_sup), 1, 0)

In [168]:
df_limpo['outlier_idade'] = detecta_outlier(df_limpo.idade)

In [169]:
df_limpo

idade  tempo_educacao        estado_civil    cor    sexo  \
0       39.0              13       Never-married  White    Male   
1       50.0              13  Married-civ-spouse  White    Male   
2       38.0               9            Divorced  White    Male   
3       53.0               7  Married-civ-spouse  Black    Male   
4       37.0              14  Married-civ-spouse  White  Female   
...      ...             ...                 ...    ...     ...   
29165   27.0              12  Married-civ-spouse  White  Female   
29166   40.0               9  Married-civ-spouse  White    Male   
29167   58.0               9             Widowed  White  Female   
29168   22.0               9       Never-married  White    Male   
29169   52.0               9  Married-civ-spouse  White  Female   

       horas_por_semana salario_anual  nome  dívida  outlier_idade  
0                    40         <=50K   NaN     NaN              0  
1                    13         <=50K   NaN     NaN              0  
2                    40         <=50K   NaN     NaN              0  
3                    40         <=50K   NaN     NaN              0  
4                    40         <=50K   NaN     NaN              0  
...                 ...           ...   ...     ...            ...  
29165                38         <=50K   NaN     NaN              0  
29166                40          >50K   NaN     NaN              0  
29167                40         <=50K   NaN     NaN              0  
29168                20         <=50K   NaN     NaN              0  
29169                40          >50K   NaN     NaN              0  

[29170 rows x 10 columns]

**10 - Escreva uma função que receba o dataframe em sua forma original e retorne o dataframe modificado, após todas as transformações dos itens acima.**

In [170]:
def faz_tudo(df):
    media_idade = df.idade.mean()
    df.idade.fillna(media_idade)
    df.idade.fillna(-1)
    df.nome.loc[np.isnan(df.nome)]
    df.nome.fillna('João')
    df.nome.fillna(-1)
    df.dívida.fillna(-1)

    mm_scaler = MinMaxScaler()
    ss_scaler = StandardScaler()
    X = df.tempo_educacao.values.reshape(-1,1)
    mm_scaler.fit(X)
    mm_scaler.transform(X)
    X2 = df.horas_por_semana.values.reshape(-1,1)
    ss_scaler.fit(X2)
    ss_scaler.transform(X2)

    ohe = OneHotEncoder()
    variavel_ohe = df.estado_civil.values.reshape(-1,1)
    ohe.fit(variavel_ohe)
    ohe.transform(variavel_ohe)
    variavel_ohe = df.cor.values.reshape(-1,1)
    ohe.fit(variavel_ohe)
    ohe.transform(variavel_ohe)
    ohe.transform(variavel_ohe).toarray()
    variavel_ohe = df.sexo.values.reshape(-1,1)
    ohe.fit(variavel_ohe)
    ohe.transform(variavel_ohe)
    ohe.transform(variavel_ohe).toarray()

    return df

In [171]:
faz_tudo(df)

idade  tempo_educacao        estado_civil    cor    sexo  \
0       39.0              13       Never-married  White    Male   
1       50.0              13  Married-civ-spouse  White    Male   
2       38.0               9            Divorced  White    Male   
3       53.0               7  Married-civ-spouse  Black    Male   
4       37.0              14  Married-civ-spouse  White  Female   
...      ...             ...                 ...    ...     ...   
29165   27.0              12  Married-civ-spouse  White  Female   
29166   40.0               9  Married-civ-spouse  White    Male   
29167   58.0               9             Widowed  White  Female   
29168   22.0               9       Never-married  White    Male   
29169   52.0               9  Married-civ-spouse  White  Female   

       horas_por_semana salario_anual  nome  dívida  outlier_idade  
0                    40         <=50K   NaN     NaN              0  
1                    13         <=50K   NaN     NaN              0  
2                    40         <=50K   NaN     NaN              0  
3                    40         <=50K   NaN     NaN              0  
4                    40         <=50K   NaN     NaN              0  
...                 ...           ...   ...     ...            ...  
29165                38         <=50K   NaN     NaN              0  
29166                40          >50K   NaN     NaN              0  
29167                40         <=50K   NaN     NaN              0  
29168                20         <=50K   NaN     NaN              0  
29169                40          >50K   NaN     NaN              0  

[29170 rows x 10 columns]